### ISSUE TITLE
Roadmap for Stripe frontend

### ISSUE THREAD

**Issue by IDerr** [edx/frontend-app-payment#493]
Hello edx team,

I would like to know if there's any plan on your roadmap to integrate Stripe in this repo.

Thanks a lot for your great work !

**Comment by pshiu** [comment]
Hi IDerr! Nice to meet you, and thanks for your question. We're not 100% sure yet, but please watch our [new commerce-coordinator repository](https://github.com/edx/commerce-coordinator/tree/main/docs/decisions) and join the [Open edX Slack](https://open.edx.org/blog/open-edx-slack/) to stay up to date on system updates as we build out the next version of our ecommerce system.
